# This configuration works with file: 

right_arm_joints:
  - joint70     # Shoulder
  - joint63     # Inner Shoulder
  - joint77     # Elbow
  - joint84     # Hand

left_arm_joints:
  - joint42     # Shoulder
  - joint35     # Inner Shoulder
  - joint49     # Elbow
  - joint56     # Hand 

spine:
  - joint70     # Pelvis Low
  - joint7      # Pelvis High
  - joint14     # Back
  - joint21     # Neck

head:
  - joint28     # Head

labels:

  rShoulder:  joint70
  rElbow:     joint77
  rWrist:     joint84
  lShoulder:  joint42
  lElbow:     joint49
  lWrist:     joint56
  Torso:      joint14
  Pelvis:     joint70
